### ISSUE TITLE
Hash this file cause explorer crash

### ISSUE THREAD

**Issue by spphinslove** [namazso/OpenHashTab#169] opened 2023-06-06 12:46 UTC
other file work fine,but this file is special
https://github.com/keepassxreboot/keepassxc/releases/download/2.7.5/KeePassXC-2.7.5-Win64.msi

version:https://github.com/namazso/OpenHashTab/actions/runs/5164482844 or **release**
OS:Win11 22H2 25352.1

**Comment by kurtmckee** [comment] 2023-06-06 19:42
What hashes do you have enabled? What options do you have enabled?

Could you take a screenshot of your OpenHashTab configuration and post it?

**Comment by spphinslove** [comment] 2023-06-08 11:47
> What hashes do you have enabled? What options do you have enabled?
> 
> Could you take a screenshot of your OpenHashTab configuration and post it?

![图片](https://github.com/namazso/OpenHashTab/assets/11383988/33ae2828-2151-4787-86c8-e5926869b93f)

**Comment by Yoti** [comment] 2023-06-09 20:27
Same here. I can open options (Alt+Enter) menu, but choosing Hash tab crashing Explorer.
```
C:\Users\Yoti>ver
Microsoft Windows [Version 10.0.22621.1778]
```

**Comment by namazso** [comment] 2023-06-28 16:31
Duplicate of #174

**Closed by namazso** 2023-06-28 16:31 UTC
