### ISSUE TITLE
Some texts in the setup is garbled when selecting Simp Chinese as setup language.

### ISSUE THREAD

**Issue by maidmeow4** [namazso/OpenHashTab#141] opened 2022-07-25 01:39 UTC
![图片](https://user-images.githubusercontent.com/8447650/180676999-66bb5a10-df15-474e-afbc-ef39fa0829e6.png)

PS: These texts display correctly under Trad Chinese and Japanese.

**Comment by namazso** [comment] 2022-07-25 08:12
duplicate of #120, already fixed

**Closed by namazso** 2022-07-25 08:12 UTC
