### ISSUE TITLE
OpenHashTab being flagged by VirusTotal

### ISSUE THREAD

**Issue by morris-t** [namazso/OpenHashTab#170] opened 2023-06-06 18:15 UTC
![Screenshot 2023-06-06 141441](https://github.com/namazso/OpenHashTab/assets/20741651/5a45d6c7-2124-4e2c-b682-2cdea0602dae)

https://www.virustotal.com/gui/file/1b5a0475b0ec3cb211e3f710fa8c0a2cd5ce971475104de91b2aeb7f865b96e6?nocache=1

**Comment by namazso** [comment] 2023-06-06 18:19
That's 3 engines no one heard of. Try contacting them, maybe you'll have more luck.

Closing because the issue is not in this software.

**Closed by namazso** 2023-06-06 18:19 UTC
