### ISSUE TITLE
vergleichen mit / Gegenprüfung! 

### ISSUE THREAD

**Issue by DARO75** [namazso/OpenHashTab#186] opened 2023-07-24 05:49 UTC
![24-07-2023_07-47-00](https://github.com/namazso/OpenHashTab/assets/8286258/30fa2e24-e798-4d8a-8089-91158e553651)

vergleichen mit / Gegenprüfung! 
How does it work, or does it work at all?

**Comment by namazso** [comment] 2023-07-24 05:52
You paste the hash in, and it lights up in the color of what kind of match it is. Below it also displays which file and algorithm produced that hash:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/dd17a46f-3bbc-4705-955e-01b196f31a49)

**Comment by DARO75** [comment] 2023-07-24 05:58
oh that's a little awkward! they cannot implement it as with HashTab?
![24-07-2023_07-57-27](https://github.com/namazso/OpenHashTab/assets/8286258/2c21b57c-bf70-4fed-be6b-b86042031b74)

**Comment by namazso** [comment] 2023-07-24 06:03
Not for now, it requires quite some refactoring (essentially rewriting the hashing engine), as it currently can't hash new files (as in, ones not known by the time of starting the hash job). I want to get around it, but it's going to take a while, it's the only part that was not rewritten since 1.0.

Duplicate of #8

**Closed by namazso** 2023-07-24 06:03 UTC

**Comment by DARO75** [comment] 2023-07-24 06:27
okay
