### ISSUE TITLE
Issue verifying hashes of big local folders

### ISSUE THREAD

**Issue by oveand** [namazso/OpenHashTab#115] opened 2022-05-08 10:59 UTC
I have some big folders, for example ~600 GB and ~30,000 files, where I've tried to make a hash for the entire folder.
The hash is created successfully but when I open the hash to verify the folder it just re-hashes the sha512 file instead of opening the file and recheck the hashes. When I open the sha512 file the content looks right.
![image](https://user-images.githubusercontent.com/13885942/167293022-bf229f55-7a4a-40cf-a98b-44a1788b544c.png)

Smaller folders and sha512 files works like a charm.

**Comment by namazso** [comment] 2022-05-08 11:04
Seems like a duplicate of #97 and already fixed on master. Try a development build and report back

**Comment by oveand** [comment] 2022-05-08 11:19
Excellent, seems to work. At least it is doing something, though the table has not been populated.

![image](https://user-images.githubusercontent.com/13885942/167293790-d00c5e5c-e70c-4360-9fce-a4470be38147.png)

**Comment by namazso** [comment] 2022-05-08 11:42
Yeah it will be populated as files finish and windows catches up (it just pumps window messages as fast as possible)

**Closed by namazso** 2022-05-08 11:42 UTC

**Comment by oveand** [comment] 2022-05-08 15:18
I can confirm that it works with development build. Thank you very much, especially for the quick response! :)
