### ISSUE TITLE
Internationalization language errors

### ISSUE THREAD

**Issue by XMuli** [namazso/OpenHashTab#176] opened 2023-07-02 14:59 UTC
In Win10 22H2, Simplified Chinese environment, the installer appears garbled

![image](https://github.com/namazso/OpenHashTab/assets/33887845/e4289172-de70-4670-9371-55e123025c9f)

![image](https://github.com/namazso/OpenHashTab/assets/33887845/39e33743-012f-4ca6-8db8-5b45d995b7a7)

**Comment by namazso** [comment] 2023-07-02 15:00
Duplicate of #152, already fixed in development version

**Closed by namazso** 2023-07-02 15:00 UTC
