### ISSUE TITLE
Installer Shows Messy Text

### ISSUE THREAD

**Issue by LenKiMo** [namazso/OpenHashTab#150] opened 2022-10-29 15:06 UTC
![2022-10-29_230414](https://user-images.githubusercontent.com/10625080/198838800-e794ef42-5938-436f-930f-f77653528688.png)

Version 3.0.2 installer cannot display text correctly on this page in Windows 11 Pro Simplified Chinese environment.

**Comment by namazso** [comment] 2022-10-29 15:08
duplicate of #120 

already fixed on master, I just haven't had time to do a bugfix release yet

**Closed by namazso** 2022-10-29 15:08 UTC
