### ISSUE TITLE
SHA-512 gives no match even when copied from the tool itself (Windows 11, 64-bit)

### ISSUE THREAD

**Issue by moebiuscorzer** [namazso/OpenHashTab#184] opened 2023-07-18 09:09 UTC
I recently downloaded the Cygwin installer on a 64-bit Windows 11 computer. The SHA-512 hash gives no match, even when I just copy the one provided by OpenHashTab and paste it.

- here is the [link to Cygwin](https://www.cygwin.com/install.html)
- here is the [link to Cygwin sha-512 hash](https://cygwin.com/sha512.sum)

<img width="271" alt="image" src="https://github.com/namazso/OpenHashTab/assets/46035379/a750b245-3d34-42d0-bfc5-52430f3fcdd0">

**Comment by namazso** [comment] 2023-07-18 09:19
Dupe of #179 

I'll release a new version this week, just rounding up any other potential issues that may have slipped in

**Closed by namazso** 2023-07-18 09:19 UTC
